services:

  backend:
    build: backend
    restart: always
    ports:
     - "8080:8080"
    networks:
      - react-spring
      - spring-mysql
    env_file:
      - .env
    
      
  
  db:
    image: mysql:latest
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./db/final_project_db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - spring-mysql
    

  frontend:
    build:
      context: frontend
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/code/src
      - /project/node_modules
    networks:
      - react-spring
    depends_on:
      - backend
    expose:
      - 3306
      - 33060

volumes:
  db:
    driver: local

networks:
  react-spring: {}
  spring-mysql: {}
